#----------------------------------------------------------
# NERD
#----------------------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
