- hosts: localhost
  connection: local
  vars:
    homebrew_taps:
      - homebrew/core
      - jesseduffield/lazydocker
      - sanemat/font

    homebrew_packages:
      - name: ansible
      - name: autoconf
      - name: automake
      - name: bash
      - name: cairo
      - name: circleci
      - name: ctags
      - name: figlet
      - name: fontconfig
      - name: fontforge
      - name: freetype
      - name: fribidi
      - name: gdbm
      - name: gettext
      - name: giflib
      - name: glib
      - name: go
      - name: graphite2
      - name: hadolint
      - name: harfbuzz
      - name: htop
      - name: icu4c
      - name: jemalloc
      - name: jpeg
      - name: jq
      - name: lazydocker
      - name: lazygit
      - name: libffi
      - name: libpng
      - name: libspiro
      - name: libtermkey
      - name: libtiff
      - name: libtool
      - name: libuninameslist
      - name: libuv
      - name: libvterm
      - name: libyaml
      - name: luajit
      - name: lzo
      - name: msgpack
      - name: ncurses
      - name: neovim
      - name: oniguruma
      - name: openssl
      - name: pango
      - name: pcre
      - name: pixman
      - name: pkg-config
      - name: python
      - name: python@2
      - name: readline
      - name: ricty
      - name: sqlite
      - name: tree
      - name: unibilium
      - name: xz
      - name: zsh

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew upgrade
      homebrew:
        upgrade_all: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

